const state={members:['Grandma','Alex'],medicines:{Grandma:[{name:'Sertraline 100mg',brand:'Zoloft · 1 tablet, once daily'}],Alex:[]},selected:'Grandma'};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderMembers(){const list=$('#memberList');list.innerHTML=state.members.map((m,i)=>`<div class="member"><span>${m[0]}</span>${m}<button data-remove="${i}" aria-label="Remove ${m}">×</button></div>`).join('');$('#membersNext').disabled=!state.members.length;}
function renderChoices(){ $('#personChoices').innerHTML=state.members.map(m=>`<button class="person-choice" data-person="${m}"><span class="avatar">${m[0]}</span><span><b>${m}</b><small>${state.medicines[m].length?state.medicines[m].length+' medicine'+(state.medicines[m].length>1?'s':''):'No medicines yet'}</small></span><i>›</i></button>`).join(''); }
function renderMeds(){const m=state.selected;$('#medsTitle').textContent=m+'’s';$('#medsEyebrow').textContent=m.toUpperCase()+' · MEDICINES';const meds=state.medicines[m];$('#medicineList').innerHTML=meds.length?meds.map(x=>`<div class="medicine"><span class="pill">▰</span><span><b>${x.name}</b><small>${x.brand}</small></span><span style="margin-left:auto">›</span></div>`).join(''):'<p class="lede" style="margin:22px 0">No medicines added yet. Add one manually or let the assistant scan a prescription.</p>';}
function renderDeals(){let all=state.members.flatMap(person=>state.medicines[person].map(x=>({...x,person})));if(!all.length)all=[{name:'Sertraline 100mg',brand:'Zoloft',person:'Grandma'}];$('#dealList').innerHTML=all.map((x,i)=>`<button class="deal" data-deal="${i}"><span class="deal-icon">▰</span><span><b>${x.name}</b><small>${x.person} · save $${i?112:370}/year</small></span><span class="price">From $${i?9:12}.40<br><small>/ 90 days</small></span></button>`).join('');}
function go(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0);}
function openModal(id){$(id).classList.add('show');$(id).setAttribute('aria-hidden','false')}function closeModals(){$$('.modal').forEach(x=>{x.classList.remove('show');x.setAttribute('aria-hidden','true')})}function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
$('#memberForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#memberName'),name=input.value.trim();if(name&&!state.members.includes(name)){state.members.push(name);state.medicines[name]=[];renderMembers();input.value='';}else if(name)toast('That person is already in your house.');});
$('#memberList').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){const m=state.members.splice(+e.target.dataset.remove,1)[0];delete state.medicines[m];renderMembers();}});$('#membersNext').onclick=()=>{renderChoices();go('choose')};$('#personChoices').addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(b){state.selected=b.dataset.person;renderMeds();go('meds')}});$('#chooseNext').onclick=()=>{renderDeals();go('deals')};
$('#showMedicineForm').onclick=()=>openModal('#medicineModal');$('#openAssistant').onclick=()=>openModal('#assistantModal');$('#helpButton').onclick=()=>openModal('#assistantModal');$$('.modal-close').forEach(x=>x.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
$('#medicineForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#medicineName').value.trim(),dose=$('#dosage').value.trim();state.medicines[state.selected].push({name,brand:dose});renderMeds();closeModals();e.target.reset();toast('Medicine added to '+state.selected+'’s list.');});
$('#getDeals').onclick=()=>{renderDeals();go('deals')};$('#dealList').addEventListener('click',e=>{const btn=e.target.closest('[data-deal]');if(btn){const all=state.members.flatMap(person=>state.medicines[person].map(x=>({...x,person})));const d=all[+btn.dataset.deal]||{name:'Sertraline 100mg',person:'Grandma'};$('#detailName').textContent=d.name;$('#detailPerson').textContent=d.person.toUpperCase();go('detail')}});$('[data-go="deals"]').onclick=()=>go('deals');$('#selectDeal').onclick=()=>toast('Deal selected — we’ll help with the next steps.');
const starter=[['Add members to my house','Who would you like to add? You can type names, nicknames, or a simple list.'],['Add medicine from a picture','Attach a prescription photo or medication list. I’ll pull out the details and ask who it belongs to.'],['Question about medicine','I can use the medicines in your house as context. What would you like to know?']];function message(text,user=false){const d=document.createElement('div');d.className='message'+(user?' user':'');d.textContent=text;$('#chatMessages').append(d);d.scrollIntoView({block:'nearest'});}function resetChat(){ $('#chatMessages').innerHTML='';message('Hi! I can help you set up your house, add prescriptions from a photo, or answer a medicine question.');$('#starterChoices').innerHTML=starter.map(([a])=>`<button class="starter" data-starter="${a}">${a} <span style="float:right">›</span></button>`).join('');}resetChat();$('#starterChoices').onclick=e=>{const b=e.target.closest('[data-starter]');if(!b)return;const pair=starter.find(x=>x[0]===b.dataset.starter);message(pair[0],true);message(pair[1]);$('#starterChoices').innerHTML='';};$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const i=$('#chatText');if(i.value.trim()){message(i.value,true);setTimeout(()=>message('I can help with that. For this prototype, try “Add medicine from a picture” to see the guided flow.'),350);i.value='';}});$('#attach').onclick=()=>{message('I attached a prescription image.',true);setTimeout(()=>message('I found Sertraline 100mg, 1 tablet once daily. Which household member should I assign it to?'),350)};
renderMembers();
