import test from 'node:test';import assert from 'node:assert/strict';
import {cents,quantity,normalizeUrl,offerKey,flattenJsonLd,isProduct,stable} from '../src/core.js';
import {EvidenceStore} from '../src/evidence.js';import {mkdtemp,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
test('exact money rejects unit fractions and malformed amounts',()=>{assert.equal(cents('$12.60'),'1260');assert.equal(cents(0),'0');assert.equal(cents('1,234.56'),'123456');for(const bad of ['-1','0.001','NaN',null,'$1x','Infinity'])assert.throws(()=>cents(bad));});
test('quantities are positive exact decimals',()=>{assert.equal(quantity('30.00'),'30');assert.equal(quantity('1.5'),'1.5');for(const bad of ['0','-1','1e3','1000001','NaN'])assert.throws(()=>quantity(bad));});
test('URL discovery preserves product variants and semantic query params',()=>{const base='https://www.healthwarehouse.com/sitemap';assert.equal(normalizeUrl('/lisinopril-20mg-tablets?qty=best&utm_source=x#info',base,'healthwarehouse')?.url,'https://www.healthwarehouse.com/lisinopril-20mg-tablets');assert.equal(normalizeUrl('/category?page=2',base,'healthwarehouse')?.url,'https://www.healthwarehouse.com/category?page=2');assert.equal(normalizeUrl('/profile/abc',base,'healthwarehouse')?.reason,'private_or_transactional');assert.equal(normalizeUrl('https://evil.example/product',base,'healthwarehouse'),null);assert.equal(normalizeUrl('javascript:alert(1)',base,'healthwarehouse'),null);assert.equal(normalizeUrl('/toys',base,'healthwarehouse')?.reason,null);assert.equal(normalizeUrl('/help',base,'healthwarehouse')?.reason,null);});
test('Product JSON-LD selection ignores organization and traverses graphs',()=>{const d=flattenJsonLd([{'@type':'Pharmacy'},{'@graph':[{'@type':['Thing','Product'],sku:'A'}]}]);assert.equal(d.filter(isProduct).length,1);assert.equal(d.filter(isProduct)[0].sku,'A');});
test('stable serialization ignores property order without changing array identity',()=>{assert.equal(stable({b:2,a:1}),stable({a:1,b:2}));assert.notEqual(stable([1,2]),stable([2,1]));});
test('immutable evidence is idempotent and content addressed',async()=>{const dir=await mkdtemp(join(tmpdir(),'housemed-evidence-'));const store=new EvidenceStore(dir);const a=await store.put('healthwarehouse','test','u',{price:'9.00'});const b=await store.put('healthwarehouse','test','u',{price:'9.00'});const c=await store.put('healthwarehouse','test','u',{price:'9.01'});assert.equal(a,b);assert.notEqual(a,c);assert.equal(JSON.parse(await readFile(join(dir,a.replace('local://','')),'utf8')).price,'9.00');});
