import {DatabaseSocket,networkFetch} from '../src/network.ts';
import pg from 'pg';import {readFile,writeFile,mkdir} from 'node:fs/promises';
process.loadEnvFile('.env.worker');const db=new pg.Client({connectionString:process.env.DATABASE_URL,stream:()=>new DatabaseSocket(),connectionTimeoutMillis:15000,ssl:{rejectUnauthorized:true,ca:await readFile('config/supabase-ca.crt','utf8')}});await db.connect();
try{const pages=(await db.query(`select s.slug as source,p.page_type,p.last_result,count(*)::int as count from pricing.crawl_pages p join pricing.sources s on s.id=p.source_id group by s.slug,p.page_type,p.last_result order by s.slug,p.page_type,p.last_result`)).rows;const runs=(await db.query(`select distinct on(source_id) s.slug as source,r.id,r.status,r.started_at,r.finished_at,r.summary from pricing.crawl_runs r join pricing.sources s on s.id=r.source_id order by source_id,started_at desc,id desc`)).rows;
const counts={};for(const table of ['listings','offers','offer_history'])counts[table]=(await db.query(`select count(*)::int n from pricing.${table}`)).rows[0].n;
async function optional(path){try{return JSON.parse(await readFile(path,'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
const pilot=await optional('data/pilot/config.json'),reliability=await optional('data/reports/reliability.json'),lastTick=await optional('data/reports/pilot-last-tick.json');
const manifest=pilot?await optional(pilot.manifest_path):null;
const report={generated_at:new Date().toISOString(),project_ref:process.env.SUPABASE_PROJECT_REF,status:'implementation_in_progress',pages,runs,counts,pilot:pilot??{enabled:false},reliability,last_tick:lastTick,acceptance:{full_site_audit:manifest?.inventory_audit_passed?'recorded_pass':'pending',listing_browser_audit:manifest?.listing_audit_passed?'recorded_pass':'pending',seven_day_window:reliability?.seven_day_collection_passed?'passed':pilot&&Date.parse(pilot.first_window_at)<=Date.now()?'in_progress':'not_started'}};await mkdir('data/reports',{recursive:true});await writeFile('data/reports/status.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}finally{await db.end();}
